[package]
name = "ch347_rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ch347_rs"
path = "src/bin/main.rs"
doc = false

[lib]
test = true
doctest = true
doc = true

[dependencies]
libc = "0.2"
